### ISSUE TITLE
cant sync

### ISSUE THREAD

**Issue by chetankapoor** [pelgrim/bucardo_docker_image#1]
[CONTAINER] Adding databases to Bucardo...
[CONTAINER] Adding db 0
Invalid type for id.
Invalid type for pass.
No such database "db"
Invalid type for dbname.
Invalid type for user.
Invalid type for host.
Connection to "db" (PostgreSQL database) as user bucardo failed.
Error was: FATAL:  Peer authentication failed for user "bucardo"

Will try to connect as user postgres and create superuser bucardo...

Connection as postgres failed, too. You may force add it with the --force argument.
Error was: FATAL:  database "user=" does not exist

[CONTAINER] Adding db 1
Invalid type for id.
Invalid type for pass.
No such database "db"
Invalid type for dbname.
Invalid type for user.
Invalid type for host.
Connection to "db" (PostgreSQL database) as user bucardo failed.
Error was: FATAL:  Peer authentication failed for user "bucardo"

Will try to connect as user postgres and create superuser bucardo...

Connection as postgres failed, too. You may force add it with the --force argument.
Error was: FATAL:  database "user=" does not exist

[CONTAINER] Adding sync0 to Bucardo...
Invalid type for sources[0].
Invalid type for sources[1].
Invalid type for sources[2].
Invalid type for sources[3].
Invalid type for sources[4].
Invalid type for sources[5].
Invalid type for sources[6].
Invalid type for sources[7].
Invalid type for sources[8].
Invalid type for sources[9].

**Comment by ABCurado** [comment]
This happens due a validation problem in: 
db_attr() {
  local database=$1
  local attr=$2
  local attr_type=$3
  ...
  case "$attr_type" in
    "string") validate_string_attr "$attr" "$value" ;;
    "list") validate_list_attr "$attr" "$value" ;;
    "integer") validate_integer_attr "$attr" "$value" ;;
    *) echo "Invalid type for $attr." 1>&2; exit 2;;
  ...
}

It retrieves the one of the database attributes from the config file and parses it based on the attribute type passed as an argument. 

The problem is this attribute type is not sent in the function call:

while [[ $db_index -lt $NUM_DBS ]]; do
    ...
    run_bucardo_command "add db db$db_id dbname=\"**$(db_attr $db_index dbname)**\" \
                                user=\"**$(db_attr $db_index user)**\" \
                                pass=\"$db_pass\" \
                                host=\"**$(db_attr $db_index host)**\""
    db_index=$(expr $db_index + 1)

**Comment by pelgrim** [comment]
@chetankapoor, I believe @ABCurado  is right. @ABCurado thanks for point the mistake, and feel free to write a PR if you want. Anyway, I will fix and test the image by the weekend.
Once again, thank you guys!
